# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
name: Ed Corcoran
description: Ed Corcoran&#39;s Portfolio
url: ejcorcoran.com

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Ed Corcoran
  email: hello@ejcorcoran.com
  uri: ejcorcoran.com
  bio: UI/UX Designer
  twitter: CorcoranEd

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure
permalink: none
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart', 'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Extending Jekyll
gems:
  - jekyll-sitemap

# # Settings for Collections
# collections:
#   projects:
#     output: true
#     permalink: /projects/:path/

# Settings for Contentful
contentful:
  spaces:
    - portfolio:
        space: yqtidmbejnor
        access_token: 6a7d44a84fc432b5c13467d857b18404cc9f705c8ad2e0dae072c78fe8e07ab1
        base_path: src

# Settings for Data Page Generator
page_gen:
  - data: contentful/spaces/portfolio.yaml
    name: title
    index_files: true
    template: project
    dir: /projects
